
import chatbot.Methods;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ArrayList;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author David
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int xMouse;
    int yMouse;
    
    test config = new test();

    public NewJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        appName = new javax.swing.JLabel();
        miniButton = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        clock = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        value = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        read = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        inputField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        closeButton1 = new javax.swing.JLabel();
        miniButton1 = new javax.swing.JLabel();
        frameDrag1 = new javax.swing.JLabel();
        appName1 = new javax.swing.JLabel();
        switch1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setText("Chat Bot");
        appName.setAlignmentY(0.0F);
        jPanel2.add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1, 50, -1));

        miniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniButtonMouseClicked(evt);
            }
        });
        jPanel2.add(miniButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 6, 10, 10));

        closeButton.setText("jLabel3");
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });
        jPanel2.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 7, 10, 10));

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        jPanel2.add(frameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        jButton1.setText("Switch");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        clock.setBackground(new java.awt.Color(0, 0, 0));
        clock.setFont(new java.awt.Font("DS-Digital", 0, 90)); // NOI18N
        clock.setForeground(new java.awt.Color(255, 255, 255));
        clock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clock.setText("12:32:22 PM");
        clock.setBorder(null);
        clock.setFocusable(false);
        clock.setOpaque(false);
        clock.setRequestFocusEnabled(false);
        jPanel2.add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 190));
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 230, 40));
        jPanel2.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 230, 40));

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saveMouseReleased(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        read.setText("Read");
        read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                readMouseReleased(evt);
            }
        });
        jPanel2.add(read, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel2.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jPanel3.add(jPanel2, "card6");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPane.setBackground(new java.awt.Color(105, 105, 105));

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(105, 105, 105));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        textArea.setForeground(new java.awt.Color(70, 173, 212));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setTabSize(4);
        textArea.setText("Bot: Hi nice to meet you I am the first generation chat bot.");
        textArea.setWrapStyleWord(true);
        textArea.setFocusable(false);
        scrollPane.setViewportView(textArea);

        jPanel1.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 720, 350));

        inputField.setBackground(new java.awt.Color(105, 105, 105));
        inputField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputField.setForeground(new java.awt.Color(70, 173, 212));
        inputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFieldActionPerformed(evt);
            }
        });
        inputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputFieldKeyPressed(evt);
            }
        });
        jPanel1.add(inputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 640, 40));

        sendButton.setBackground(new java.awt.Color(0, 0, 0));
        sendButton.setForeground(new java.awt.Color(70, 173, 212));
        sendButton.setText("Send");
        sendButton.setToolTipText("Click to send");
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        jPanel1.add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 70, 40));

        closeButton1.setText("jLabel3");
        closeButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButton1MouseClicked(evt);
            }
        });
        jPanel1.add(closeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 7, 10, 10));

        miniButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniButton1MouseClicked(evt);
            }
        });
        jPanel1.add(miniButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 6, 10, 10));

        frameDrag1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDrag1MouseDragged(evt);
            }
        });
        frameDrag1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDrag1MousePressed(evt);
            }
        });
        jPanel1.add(frameDrag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        appName1.setForeground(new java.awt.Color(255, 255, 255));
        appName1.setText("Chat Bot");
        appName1.setAlignmentY(0.0F);
        jPanel1.add(appName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1, 50, -1));

        switch1.setText("Switch");
        switch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                switch1MouseReleased(evt);
            }
        });
        jPanel1.add(switch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jPanel3.add(jPanel1, "card7");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void miniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniButtonMouseClicked
        this.setState(NewJFrame.ICONIFIED);
    }//GEN-LAST:event_miniButtonMouseClicked

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    private void inputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFieldActionPerformed

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        chatbot();
        inputField.setText("");
        inputField.requestFocus();
    }//GEN-LAST:event_sendButtonMouseClicked

    private void inputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            chatbot();
            inputField.setText("");
            inputField.requestFocus();
        }
    }//GEN-LAST:event_inputFieldKeyPressed

    private void closeButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButton1MouseClicked

    private void miniButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniButton1MouseClicked
        this.setState(NewJFrame.ICONIFIED);
    }//GEN-LAST:event_miniButton1MouseClicked

    private void frameDrag1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDrag1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDrag1MouseDragged

    private void frameDrag1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDrag1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDrag1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel1);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_jButton1MouseReleased

    private void switch1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switch1MouseReleased
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();

        jPanel3.add(jPanel2);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_switch1MouseReleased

    private void saveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseReleased
        String first = title.getText();
        String second = value.getText();
        config.saveProp(first, second);
    }//GEN-LAST:event_saveMouseReleased

    private void readMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readMouseReleased
        String a = title.getText();
        System.out.println(config.getProp(a));
    }//GEN-LAST:event_readMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    public void chatbot() {
        String fileGreetings = System.getProperty("user.dir") + "\\replies\\greetings.txt";
        String fileJokes = System.getProperty("user.dir") + "\\replies\\jokes.txt";

        // For random numbers
        Random randomGenerator = new Random();
        DateTimeFormatter date = DateTimeFormatter.ofLocalizedDate(FormatStyle.FULL);
        DateTimeFormatter time = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT);
        LocalDateTime currentDateTime = LocalDateTime.now();
        Methods methods = new Methods();
        ArrayList<String> greetings = new ArrayList<>();
        ArrayList<String> jokes = new ArrayList<>();

        // Replies
        String help = "Bot:        Commands avaliable\n"
                + "--------------------------------------------\n"
                + "help	  - displays this message\n"
                + "clear	  - clears the screen\n"
                + "date time\t  - shows the current date and time\n"
                + "date 	  - shows the current date\n"
                + "time	  - shows the current time\n"
                + "encode	  - converts a decimal number to binary/hexadecimal\n"
                + "decode	  - converts a binary/hexadecimal number to decimal\n"
                + "coin flip\t  - flips a coin\n"
                + "joke\t  - tells a joke\n"
                + "exit	  - closes the program\n";
        String[] defaultReply = {"What chu say boi", "Talk shit get hit", "I don't understand", "Do Rei Me Fa So Fucking Done with you.",
            "Are you speaking english?"};
        String[] goodbye = {"Okay bye~", "See you again", "Goodbye"};

        // Read replies from file for greetings
        try {

            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(fileGreetings)));
            String line;

            while ((line = br.readLine()) != null) {
                greetings.add(line);
            }
            br.close();

        } catch (IOException e) {
            System.out.println("ERROR: unable to read file " + fileGreetings);
        }

        // Read replies from file for jokes
        try {

            BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(fileJokes)));
            String line;

            while ((line = br.readLine()) != null) {
                jokes.add(line);
            }
            br.close();

        } catch (IOException e) {
            System.out.println("ERROR: unable to read file " + fileGreetings);
        }

        String input = inputField.getText();
        String lowerCaseInput = input.toLowerCase();
        textArea.append("You: " + input + "\n");
        switch (lowerCaseInput) {
            // Commands
            case "exit":
                System.exit(0);
                break;
            case "clear":
                textArea.setText("");
                break;
            case "help":
                textArea.append(help);
                break;
            case "date time":
            case "date and time":
                textArea.append("Bot: Today is " + date.format(currentDateTime) + " and the time now is " + time.format(currentDateTime) + "\n");
                break;
            case "date":
            case "what is the date":
                textArea.append("Bot: Today is " + date.format(currentDateTime) + "\n");
                break;
            case "time":
            case "what is the time now":
                textArea.append("Bot: The time is " + time.format(currentDateTime) + "\n");
                break;
            case "encode":
                methods.Decimal2Bin();
                break;
            case "decode":
                methods.decode();
                break;
            case "coin flip":
                textArea.append("Bot: " + methods.coinFlip() + "\n");
                break;
            // Convos
            case "bye":
                textArea.append("Bot: " + goodbye[randomGenerator.nextInt(3)] + "\n");
                break;
            case "okay":
                textArea.append("Bot: Okay\n");
                break;
            // Questions
            case "what is an issue":
                textArea.append("Bot: An issue is something that can be debated.\n");
                break;
            case "what is a stakeholder":
                textArea.append("Bot: People who are related/affected by the issue.\n");
                break;
            case "what is your name":
                textArea.append("Bot: I dont\'t have a name\n");
                break;
            // Greetings
            case "hey":
            case "sup":
            case "hello":
            case "hi":
                textArea.append("Bot: " + greetings.get(randomGenerator.nextInt(greetings.size())) + "\n");
                break;
            // Nice stuff
            case "sorry":
                textArea.append("Bot: Naww don't be!\n");
                break;
            case "i love you":
                textArea.append("Bot: Aww love you too <3\n");
                break;
            case "how are you doing":
            case "how are you":
                textArea.append("Bot: I'm doing well thankyou\n");
                break;
            case "thanks":
            case "thx":
                textArea.append("Bot: No problem!\n");
                break;
            // Misc
            case "cheer time":
                textArea.append("Bot: ECHO AFTER ME AH\n");
                break;
            case "joke":
            case "tell me a joke":
                textArea.append("Bot: " + jokes.get(randomGenerator.nextInt(jokes.size())) + "\n");
                break;
            default:
                textArea.append("Bot: " + defaultReply[randomGenerator.nextInt(5)] + "\n");
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appName;
    private javax.swing.JLabel appName1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JTextField clock;
    private javax.swing.JLabel closeButton;
    private javax.swing.JLabel closeButton1;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel frameDrag1;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel miniButton;
    private javax.swing.JLabel miniButton1;
    private javax.swing.JButton read;
    private javax.swing.JButton save;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton switch1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField title;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
